services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - mcp-network

  ollama-ui:
    image: ghcr.io/ollama-webui/ollama-webui:latest
    container_name: ollama-ui
    ports:
      - "3000:8080"
    environment:  
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mcp-network

  mcp-calculator:
    build: .
    container_name: mcp-calculator
    volumes:
      - ./src/main/java:/scripts/java
    environment:
      - INPUT_SCRIPT=/scripts/java/MCPCalculator.java
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - mcp-network

volumes:
  ollama_data:

networks:
  mcp-network:
    driver: bridge 